<?php
/**
 * @file
 * nb_openid_provider.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function nb_openid_provider_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
  list($module, $api) = func_get_args();
  if ($module == "oauthconnector" && $api == "") {
    return array("version" => "");
  }
  list($module, $api) = func_get_args();
  if ($module == "oauthconnector" && $api == "oauthconnector") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function nb_openid_provider_views_api() {
  return array("api" => "3.0");
}
